on:
  pull_request:

jobs:
  test:
    name: test
    # Specify OS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D clippy::all
      - run: cargo test